# Application Configuration
app:
  name: face-service
  port: 8086
  address: 192.168.161.1

# PostgreSQL Configuration
database:
  url: jdbc:postgresql://db.nzxeumzixerxyzdlscjz.supabase.co:5432/postgres?currentSchema=face_db
  username: postgres
  password: Minhtri@123
  driver-class-name: org.postgresql.Driver
  schema: face_db

# Redis Configuration
redis:
  host: localhost
  port: 6379
  timeout: 60000

# NATS Configuration
nats:
  server:
    url: nats://localhost:4222
  subjects:
    face-verification-success: face.verification.success
    face-verification-failed: face.verification.failed

# Logging Configuration
logging:
  level:
    root: INFO
    app: DEBUG
  file:
    name: logs/face-service.log

# Eureka Configuration 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${app.name}:${app.port}