server:
  port: 8443
  address: 0.0.0.0
  forward-headers-strategy: framework
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      forwarded:
        enabled: true
      x-forwarded:
        enabled: true
        for-enabled: true
        host-enabled: true
        port-enabled: true
        proto-enabled: true
        prefix-enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: class-route
          uri: lb://class-service
          predicates:
            - Path=/classes/**, /schedules/**, /enrollments/**
        - id: attendance-route
          uri: lb://attendance-service
          predicates:
            - Path=/attendances/**, /qr/**
        # Route cho WebSocket notifications
#        - id: notification-websocket
#          uri: lb://notification-service
#          predicates:
#            - Path=/ws-notifications/**
#          filters:
#            - RewritePath=/ws-notifications/(?<segment>.*), /ws-notifications/$\{segment}
        #Route cho Notification service
        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - RewritePath=/notifications/(?<segment>.*), /$\{segment}
      global-filter:
        websocket-routing:
          enabled: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://192.168.1.4:8761/eureka
#      defaultZone: http://172.20.10.6:8761/eureka
#      defaultZone: http://192.168.83.246:8761/eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: LJ8WPZjFNSfnoD5g+JZXSFiQaMY6gfNvBfR8w9HwT9OI0yEg2RfH2t9mpR7C2Ij7