server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: class-route
          uri: lb://class-service
          predicates:
            - Path=/classes/**, /schedules/**, /enrollments/**
        - id: attendance-route
          uri: lb://attendance-service
          predicates:
            - Path=/attendances/**, /qr/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.161.1:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: LJ8WPZjFNSfnoD5g+JZXSFiQaMY6gfNvBfR8w9HwT9OI0yEg2RfH2t9mpR7C2Ij7