server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
