eureka:
  instance:
    hostname: 192.168.1.4
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

server:
  port: 8761